server:
  port: 7800
spring:
  redis:
    database: 11
    port: 6379
    host: 1.13.4.35
  elasticsearch:
    rest:
      uris: http://192.168.50.212:9200
  application:
    name: gateway
  cloud:
    gateway: # 配置gateway相关属性
      discovery: # 配置网关发现机制
        locator: # 配置处理机制
          enabled: true # 开启网关自动映射处理逻辑, 只要请求地址符合规则
          # http://gatewayIP:gatewayPort/微服务名称/微服务请求地址
          # 网关自动映射, 请求转发到http://微服务名称/微服务请求地址
          # 请求地址: http://localhost:9999/front/
          # 转发地址: http://front
          lower-case-service-id: true
#      routes:
#
#        - id: test
#          uri: lb://front-page # 当前的路由定义对应的微服务转发地址
#          predicates:
#            - Path=/front/**
##          filters: # 配置过滤器集合
#            # 过滤器转发地址前缀, 过滤1节
#            # 如: 请求地址 - http://localhost:9999/api/getArgs?name=admin&age=20
#            # 对应的谓词, 规则是/api, 符合
#            # 对应的uri是 lb://ribbon-app-service 转换成 http://ribbon-app-service
#            # 转发地址是: http://ribbon-app-service/api/getArgs?name=admin&age=20
#            # 过滤器是过滤转发地址的前缀, 过滤第1节, 即删除/api -> http://ribbon-service/getArgs?name=admin&age=20
##            - StripPrefix=1

eureka:
  instance:
    instance-id: gateway
  client:
    service-url:
      defaultZone: http://1.13.4.35:9001/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug