spring:
  profiles: eureka-server3
  application:
    name: eureka-server3
server:
  port: 9003
eureka:
  instance:
    hostname: eureka8003
#    prefer-ip-address: true
#    instance-id: 192.168.50.218:9003
    instance-id: eureka8003:9003
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka8002:9002/eureka/, http://eureka8001:9001/eureka/