spring:
  profiles: eureka-server1
  application:
    name: eureka-server1
server:
  port: 9001
eureka:
  instance:
#    hostname: eureka8001.com
    prefer-ip-address: true
    instance-id: 192.168.50.218:9001
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.50.218:9002/eureka/,http://192.168.50.218:9003/eureka/