spring:
  profiles: eureka-server2
  application:
    name: eureka-server2
server:
  port: 9002
eureka:
  instance:
#    prefer-ip-address: true
#    instance-id: 192.168.50.218:9002
    hostname: eureka8002
    instance-id: eureka8002:9002
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka8001:9001/eureka/, http://eureka8003:9003/eureka/